# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import meta.models
import mptt.fields
import page_editor.widgets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageBrowser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Редактор файлов',
                'verbose_name_plural': 'Редактор файлов',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=100, verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', page_editor.widgets.PRNotesField(blank=True, verbose_name='content')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_date', models.DateTimeField(auto_now=True, null=True)),
                ('show_in_menu', models.BooleanField(default=True, help_text='Показывать данную страницу в меню сайта', verbose_name='Показывать в меню')),
                ('dynamic', models.BooleanField(default=False, help_text='Страница с диномическим контентом', verbose_name='Динамическая')),
                ('static', models.BooleanField(default=True, help_text='Страница с статическим контентом', verbose_name='Статическая')),
                ('html_render', models.TextField(blank=True, null=True, verbose_name='Внутренние элементы')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='SEO Описание')),
                ('seo_keywords', models.TextField(blank=True, verbose_name='SEO слова')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='page_editor.Page', verbose_name='Родительская страница')),
            ],
            options={
                'verbose_name': 'Cтраница',
                'verbose_name_plural': 'Страницы',
                'ordering': ('url',),
            },
            bases=(models.Model, meta.models.ModelMeta),
        ),
    ]
