# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'managed': False, 'verbose_name': 'Cтраница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='pagebrowser',
            options={'managed': False, 'verbose_name': 'Редактор файлов', 'verbose_name_plural': 'Редактор файлов'},
        ),
    ]
