# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_editor', '0002_auto_20170803_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('url',), 'verbose_name': 'Cтраница', 'verbose_name_plural': 'Страницы'},
        ),
    ]
