# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import page_editor.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('page_editor', '0003_auto_20170813_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='template_name',
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=page_editor.widgets.PRNotesField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_home',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Главная'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='page_editor.Page', verbose_name='Родительская страница'),
        ),
    ]
