# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_editor', '0005_auto_20170913_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='html_render',
            field=models.TextField(blank=True, null=True, verbose_name='Внутренние элементы'),
        ),
    ]
