# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_editor', '0006_auto_20170914_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_in_menu',
            field=models.BooleanField(default=True, help_text='Показывать данную страницу в меню сайта', verbose_name='Показывать в меню'),
        ),
    ]
