# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('page_editor', '0007_page_show_in_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='seo_description',
            field=models.TextField(blank=True, null=True, verbose_name='SEO Описание'),
        ),
        migrations.AddField(
            model_name='page',
            name='seo_keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='SEO слова'),
        ),
    ]
