# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_editor', '0008_auto_20170915_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='seo_keywords',
        ),
        migrations.AddField(
            model_name='page',
            name='seo_keywords',
            field=models.TextField(blank=True, verbose_name='SEO слова'),
        ),
    ]
