# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_editor', '0009_auto_20170916_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='static',
            field=models.BooleanField(default=True, help_text='Страница с статическим контентом', verbose_name='Статическая'),
        ),
    ]
