# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=11, max_length=300, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
