# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20170920_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='text_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
