# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20170813_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='order',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='order',
        ),
        migrations.AddField(
            model_name='text',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='text', to='order.Task'),
        ),
        migrations.AddField(
            model_name='todo',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='order.Task'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='order.Order'),
        ),
    ]
