# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20170813_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='order.Order'),
        ),
        migrations.AlterField(
            model_name='text',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='order.Task'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='order.Task'),
        ),
    ]
