# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20170813_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.RemoveField(
            model_name='text',
            name='user',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
