# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20170901_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
