# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20170905_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentfiles',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='order.Comment'),
        ),
    ]
